[package]
name = "starbar"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
tokio = { version = "1.44.2", features = ["time"] }
serde = {version="1.0", features = ["derive"]}
toml = "0.9.8"
gtk4 = "0.10.3"
gtk4-layer-shell = "0.7.1"
gio = "0.21.5"
